In [36]:
import pandas as pd
import numpy as np
import csv
from PIL import Image
import glob
from tqdm import trange
from tqdm import tqdm
import json

In [5]:
#vectorize image test and convert to grayscale
image = Image.open('3767841911_6678052eb6.jpg').convert('L')
arr = np.array(image)
arr.shape

(353, 500)

In [6]:
print(arr[0:10])

[[18 19 24 ... 14 10  7]
 [15 15 15 ... 19 19 17]
 [17 14 14 ... 32 35 34]
 ...
 [11 10 13 ... 12 14 16]
 [ 5 14 15 ...  4  5  5]
 [ 8 12 10 ...  3  3  4]]


In [41]:
#write loop
image_dict = {}
#get image title
directory_path = '/Users/ours/Desktop/Image Description Capstone/Flickr 8k/Images'
jpg_files = glob.glob(f'{directory_path}/*.jpg')

for i in trange(len(jpg_files)):
    file_name = jpg_files[i]
    #get image 
    image = Image.open(file_name).convert('L')

    #process image
    arr = np.array(image).tolist()
    #write to dict
    image_dict[file_name] = arr

100%|██████████████████████████████████████| 8091/8091 [01:19<00:00, 102.00it/s]


In [42]:
#took 7 min to write
with open('preprocessed_image_v1.json', 'w') as fp:
    json.dump(image_dict, fp)