In [15]:
import pandas as pd
import numpy as np
import csv
from PIL import Image
import glob
from tqdm import trange
from tqdm import tqdm
import json
import os
import cv2

In [5]:
#vectorize image test and convert to grayscale
image = Image.open('3767841911_6678052eb6.jpg').convert('L')
arr = np.array(image)
arr.shape

(353, 500)

In [6]:
print(arr[0:10])

[[18 19 24 ... 14 10  7]
 [15 15 15 ... 19 19 17]
 [17 14 14 ... 32 35 34]
 ...
 [11 10 13 ... 12 14 16]
 [ 5 14 15 ...  4  5  5]
 [ 8 12 10 ...  3  3  4]]


In [17]:
#write loop
image_dict = {}

#target size
target = (224,224)
#get image title
directory_path = '/Users/ours/Desktop/Image Description Capstone/Flickr 8k/Images'
jpg_files = glob.glob(f'{directory_path}/*.jpg')

for i in trange(len(jpg_files)):
    file_name = jpg_files[i]
    #get image 
    image = Image.open(file_name).convert('L')
    
    # Get image name without the path
    image_name = os.path.basename(file_name)

    # #process image
    # arr = np.array(image).tolist()
    
    # Resize the image using OpenCV
    resized_image = cv2.resize(np.array(image), target, interpolation=cv2.INTER_AREA)
    
    #write to dict
    image_dict[image_name] = resized_image.tolist()

100%|██████████████████████████████████████| 8091/8091 [00:44<00:00, 181.96it/s]


In [18]:
shapes = []
for key in list(image_dict.keys()):
    s = np.array(image_dict[key]).shape
    shapes.append(s)

In [19]:
np.unique(shapes)

array([224])

In [11]:
shapes = []
for key in list(image_dict.keys()):
    s = np.array(image_dict[key]).shape
    shapes.append(s)

In [13]:
np.unique(shapes)

array([127, 148, 151, 164, 166, 167, 175, 176, 177, 178, 180, 182, 183,
       185, 187, 191, 192, 193, 195, 197, 198, 200, 201, 202, 203, 207,
       208, 209, 212, 213, 214, 215, 216, 217, 218, 219, 224, 228, 229,
       230, 231, 232, 233, 237, 238, 239, 240, 241, 242, 243, 244, 245,
       246, 247, 248, 249, 250, 251, 252, 253, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 266, 267, 268, 269, 270, 271, 272, 273,
       274, 275, 276, 277, 279, 280, 281, 282, 283, 284, 285, 286, 287,
       288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300,
       301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313,
       314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326,
       327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339,
       340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352,
       353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365,
       366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 37

In [20]:
#took 7 min to write
with open('preprocessed_image_v3.json', 'w') as fp:
    json.dump(image_dict, fp)

In [8]:
#took 7 min to write
with open('preprocessed_image_v2.json', 'w') as fp:
    json.dump(image_dict, fp)

In [42]:
#took 7 min to write
with open('preprocessed_image_v1.json', 'w') as fp:
    json.dump(image_dict, fp)